"use strict";

(function exposeGameData(global) {
  const ACCESSED_DATE = "2026-07-25";
  const DEFAULT_MAX_TAG_BURDEN_PERCENT = 2;

  const SCIENCE_SOURCES = Object.freeze({
    innovasea69: {
      id: "innovasea69",
      title: "Coded Transmitters – 69 kHz (DOC-6948-10)",
      organization: "Innovasea",
      publicationYear: 2025,
      accessedDate: ACCESSED_DATE,
      url: "https://www.innovasea.com/wp-content/uploads/2026/02/Coded_Tags_69kHz_6948_10_1025.pdf",
      type: "manufacturer"
    },
    innovaseaTags: {
      id: "innovaseaTags",
      title: "Acoustic Tags",
      organization: "Innovasea",
      accessedDate: ACCESSED_DATE,
      url: "https://www.innovasea.com/fish-tracking/tags/",
      type: "manufacturer"
    },
    jepsen2005: {
      id: "jepsen2005",
      title: "A brief discussion on the 2% tag/bodymass rule of thumb",
      organization: "FAO / DTU",
      publicationYear: 2005,
      accessedDate: ACCESSED_DATE,
      url: "https://orbit.dtu.dk/en/publications/a-brief-discussion-on-the-2-tagbodymass-rule-of-thumb/",
      type: "peer-reviewed"
    },
    externalAttachment2022: {
      id: "externalAttachment2022",
      title: "Evaluation of six methods for external attachment of electronic tags to fish",
      organization: "NOAA Institutional Repository",
      publicationYear: 2022,
      accessedDate: ACCESSED_DATE,
      url: "https://repository.library.noaa.gov/view/noaa/44463",
      type: "peer-reviewed"
    },
    herring: fishBaseSource("Clupea harengus", "https://www.fishbase.se/summary/Clupea-harengus.html"),
    sprat: fishBaseSource("Sprattus sprattus", "https://www.fishbase.se/summary/Sprattus-sprattus.html"),
    mackerel: fishBaseSource("Scomber scombrus", "https://www.fishbase.se/summary/Scomber-scombrus.html"),
    cod: fishBaseSource("Gadus morhua", "https://www.fishbase.se/summary/Gadus-morhua.html"),
    haddock: fishBaseSource("Melanogrammus aeglefinus", "https://www.fishbase.se/summary/Melanogrammus-aeglefinus.html"),
    plaice: fishBaseSource("Pleuronectes platessa", "https://www.fishbase.se/summary/Pleuronectes-platessa.html"),
    salmon: fishBaseSource("Salmo salar", "https://www.fishbase.se/summary/Salmo-salar.html"),
    eel: fishBaseSource("Anguilla anguilla", "https://www.fishbase.se/summary/Anguilla-anguilla.html"),
    seabass: fishBaseSource("Dicentrarchus labrax", "https://www.fishbase.se/summary/Dicentrarchus-labrax.html"),
    dogfish: fishBaseSource("Squalus acanthias", "https://www.fishbase.se/summary/Squalus-acanthias.html"),
    catshark: fishBaseSource("Scyliorhinus canicula", "https://www.fishbase.se/summary/Scyliorhinus-canicula.html"),
    tope: fishBaseSource("Galeorhinus galeus", "https://www.fishbase.se/summary/Galeorhinus-galeus.html"),
    thornback: fishBaseSource("Raja clavata", "https://www.fishbase.se/summary/Raja-clavata.html"),
    spottedRay: fishBaseSource("Raja montagui", "https://www.fishbase.se/summary/Raja-montagui.html"),
    pollack: fishBaseSource("Pollachius pollachius", "https://www.fishbase.se/summary/Pollachius-pollachius.html")
  });

  function fishBaseSource(scientificName, url) {
    return {
      id: scientificName.toLowerCase().replace(/\s+/g, "-"),
      title: `${scientificName} species summary`,
      organization: "FishBase",
      accessedDate: ACCESSED_DATE,
      url,
      type: "species-database"
    };
  }

  const TAG_CATALOGUE = Object.freeze([
    tag({
      id: "v6",
      educationalName: { en: "Micro acoustic tag", de: "Mikro-Akustiksender" },
      referenceModel: "V6-2x",
      diameterMm: 6.3,
      lengthMm: 13,
      weightInAirGrams: 0.9,
      weightInWaterGrams: 0.5,
      batteryDays: 202,
      sensors: [],
      outputClass: "low",
      outputDb: "137 / 141",
      attachmentTypes: ["internal"],
      visualWidth: 34
    }),
    tag({
      id: "v7tp",
      educationalName: { en: "Mini sensor tag", de: "Mini-Sensorsender" },
      referenceModel: "V7TP-2x",
      diameterMm: 7,
      lengthMm: 21,
      weightInAirGrams: 1.7,
      weightInWaterGrams: 0.8,
      batteryDays: 244,
      sensors: ["temperature", "depth"],
      outputClass: "low",
      outputDb: "137 / 141",
      attachmentTypes: ["internal"],
      visualWidth: 42
    }),
    tag({
      id: "v9",
      educationalName: { en: "Small acoustic tag", de: "Kleiner Akustiksender" },
      referenceModel: "V9-1x",
      diameterMm: 9,
      lengthMm: 24,
      weightInAirGrams: 3.6,
      weightInWaterGrams: 2,
      batteryDays: 648,
      sensors: [],
      outputClass: "standard",
      outputDb: "146 / 151",
      attachmentTypes: ["internal"],
      visualWidth: 50
    }),
    tag({
      id: "v9tp",
      educationalName: { en: "Small sensor tag", de: "Kleiner Sensorsender" },
      referenceModel: "V9TP-2x",
      diameterMm: 9,
      lengthMm: 31,
      weightInAirGrams: 4.9,
      weightInWaterGrams: 2.8,
      batteryDays: 730,
      sensors: ["temperature", "depth"],
      outputClass: "standard",
      outputDb: "146 / 151",
      attachmentTypes: ["internal"],
      visualWidth: 56
    }),
    tag({
      id: "v13",
      educationalName: { en: "Medium acoustic tag", de: "Mittlerer Akustiksender" },
      referenceModel: "V13-1x",
      diameterMm: 13,
      lengthMm: 31.5,
      weightInAirGrams: 9.4,
      weightInWaterGrams: 4.4,
      batteryDays: 1825,
      sensors: [],
      outputClass: "standard",
      outputDb: "147 / 152",
      attachmentTypes: ["internal"],
      visualWidth: 64
    }),
    tag({
      id: "v13tp",
      educationalName: { en: "Medium sensor tag", de: "Mittlerer Sensorsender" },
      referenceModel: "V13TP-1x",
      diameterMm: 13,
      lengthMm: 41.5,
      weightInAirGrams: 11.3,
      weightInWaterGrams: 5.5,
      batteryDays: 1347,
      sensors: ["temperature", "depth"],
      outputClass: "standard",
      outputDb: "147 / 152",
      attachmentTypes: ["internal"],
      visualWidth: 72
    }),
    tag({
      id: "v16",
      educationalName: { en: "Large acoustic tag", de: "Großer Akustiksender" },
      referenceModel: "V16-4x",
      diameterMm: 16,
      lengthMm: 68,
      externalDiameterMm: 18,
      externalLengthMm: 89,
      weightInAirGrams: 24,
      weightInWaterGrams: 10.3,
      batteryDays: 3650,
      sensors: [],
      outputClass: "high",
      outputDb: "152 / 158",
      attachmentTypes: ["internal", "external"],
      visualWidth: 86
    }),
    tag({
      id: "v16tp",
      educationalName: { en: "Large sensor tag", de: "Großer Sensorsender" },
      referenceModel: "V16TP-4x",
      diameterMm: 16,
      lengthMm: 71,
      externalDiameterMm: 18,
      externalLengthMm: 92,
      weightInAirGrams: 26,
      weightInWaterGrams: 12,
      batteryDays: 3650,
      sensors: ["temperature", "depth"],
      outputClass: "high",
      outputDb: "152 / 158",
      attachmentTypes: ["internal", "external"],
      visualWidth: 90
    })
  ]);

  function tag(data) {
    return Object.freeze({
      frequencyKhz: 69,
      sourceIds: ["innovasea69", "innovaseaTags"],
      ...data
    });
  }

  const STUDY_REQUIREMENTS = Object.freeze({
    shortPresence: requirement({
      id: "shortPresence",
      title: { en: "Short seasonal presence study", de: "Kurze saisonale Studie" },
      summary: { en: "Track presence for about three months with low output.", de: "Anwesenheit etwa drei Monate lang mit niedriger Sendeleistung erfassen." },
      minimumBatteryDays: 90,
      requiredSensors: [],
      attachmentType: "internal",
      outputClass: "low"
    }),
    temperatureSeason: requirement({
      id: "temperatureSeason",
      title: { en: "Seasonal temperature study", de: "Saisonale Temperaturstudie" },
      summary: { en: "Record temperature for roughly six months.", de: "Temperatur ungefähr sechs Monate lang erfassen." },
      minimumBatteryDays: 200,
      requiredSensors: ["temperature"],
      attachmentType: "internal",
      outputClass: "low"
    }),
    migrationYear: requirement({
      id: "migrationYear",
      title: { en: "One-year migration study", de: "Einjährige Wanderstudie" },
      summary: { en: "Follow broad movement for at least 600 days at standard output.", de: "Großräumige Bewegungen mindestens 600 Tage lang mit Standardleistung verfolgen." },
      minimumBatteryDays: 600,
      requiredSensors: [],
      attachmentType: "internal",
      outputClass: "standard"
    }),
    depthYear: requirement({
      id: "depthYear",
      title: { en: "Depth-use study", de: "Studie zur Tiefennutzung" },
      summary: { en: "Measure depth for at least 500 days at standard output.", de: "Tiefe mindestens 500 Tage lang mit Standardleistung messen." },
      minimumBatteryDays: 500,
      requiredSensors: ["depth"],
      attachmentType: "internal",
      outputClass: "standard"
    }),
    longMigration: requirement({
      id: "longMigration",
      title: { en: "Multi-year migration study", de: "Mehrjährige Wanderstudie" },
      summary: { en: "Track movement for at least 1,000 days.", de: "Bewegungen mindestens 1.000 Tage lang verfolgen." },
      minimumBatteryDays: 1000,
      requiredSensors: [],
      attachmentType: "internal",
      outputClass: "standard"
    }),
    longTemperature: requirement({
      id: "longTemperature",
      title: { en: "Long temperature study", de: "Langzeit-Temperaturstudie" },
      summary: { en: "Measure temperature for at least 1,200 days.", de: "Temperatur mindestens 1.200 Tage lang messen." },
      minimumBatteryDays: 1200,
      requiredSensors: ["temperature"],
      attachmentType: "internal",
      outputClass: "standard"
    }),
    externalLong: requirement({
      id: "externalLong",
      title: { en: "Long movement study", de: "Langzeitstudie mit Befestigung" },
      summary: { en: "Use an high-output tag for at least 1,500 days.", de: "Einen Hochleistungssender mindestens 1.500 Tage lang verwenden." },
      minimumBatteryDays: 1500,
      requiredSensors: [],
      attachmentType: "external",
      outputClass: "high"
    }),
    externalDepth: requirement({
      id: "externalDepth",
      title: { en: " depth-use study", de: " Studie zur Tiefennutzung" },
      summary: { en: "Use an high-output depth tag for at least 1,000 days.", de: "Einen Tiefensender mit hoher Leistung mindestens 1.000 Tage lang verwenden." },
      minimumBatteryDays: 1000,
      requiredSensors: ["depth"],
      attachmentType: "external",
      outputClass: "high"
    })
  });

  function requirement(data) {
    return Object.freeze({ environment: "marine", ...data });
  }

  const FISH_CARDS = Object.freeze([
    fish({
      id: "herring-rose",
      individualName: "Rose",
      commonName: { en: "Atlantic herring", de: "Atlantischer Hering" },
      scientificName: "Clupea harengus",
      taxonomicGroup: "teleost",
      lengthCm: 12.5,
      lengthType: "total",
      weightGrams: 18,
      lifeStage: "juvenile",
      habitatSummary: { en: "Coastal nursery waters", de: "Küstennahe Aufwuchsgebiete" },
      behaviorSummary: { en: "Schools closely with other young herring.", de: "Schwimmt eng mit anderen jungen Heringen im Schwarm." },
      visualKey: "herring",
      illustrationAltText: { en: "Slender silver herring with a blue-green back and forked tail", de: "Schlanker silbriger Hering mit blaugrünem Rücken und gegabelter Schwanzflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 6.3,
      anatomicalTagLengthLimitMm: 15,
      studyRequirementId: "shortPresence",
      sourceIds: ["herring", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "herring-henk",
      individualName: "Henk",
      commonName: { en: "Atlantic herring", de: "Atlantischer Hering" },
      scientificName: "Clupea harengus",
      taxonomicGroup: "teleost",
      lengthCm: 27,
      lengthType: "total",
      weightGrams: 120,
      lifeStage: "adult",
      habitatSummary: { en: "Open coastal water", de: "Offenes Küstenwasser" },
      behaviorSummary: { en: "Moves between feeding and spawning grounds in schools.", de: "Zieht in Schwärmen zwischen Nahrungs- und Laichgebieten." },
      visualKey: "herring",
      illustrationAltText: { en: "Adult Atlantic herring with silvery compressed body and forked tail", de: "Erwachsener Atlantischer Hering mit silbrig abgeflachtem Körper und gegabelter Schwanzflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 6.3,
      anatomicalTagLengthLimitMm: 14,
      studyRequirementId: "shortPresence",
      sourceIds: ["herring", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "sprat-noor",
      individualName: "Noor",
      commonName: { en: "European sprat", de: "Europäische Sprotte" },
      scientificName: "Sprattus sprattus",
      taxonomicGroup: "teleost",
      lengthCm: 9.5,
      lengthType: "total",
      weightGrams: 12,
      lifeStage: "juvenile",
      habitatSummary: { en: "Shallow coastal water", de: "Flaches Küstenwasser" },
      behaviorSummary: { en: "Forms dense schools and feeds on plankton.", de: "Bildet dichte Schwärme und frisst Plankton." },
      visualKey: "sprat",
      illustrationAltText: { en: "Small silver sprat with a narrow body and sharply forked tail", de: "Kleine silbrige Sprotte mit schmalem Körper und stark gegabelter Schwanzflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 6,
      anatomicalTagLengthLimitMm: 13,
      studyRequirementId: "shortPresence",
      sourceIds: ["sprat", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "mackerel-marta",
      individualName: "Marta",
      commonName: { en: "Atlantic mackerel", de: "Atlantische Makrele" },
      scientificName: "Scomber scombrus",
      taxonomicGroup: "teleost",
      lengthCm: 38,
      lengthType: "fork",
      weightGrams: 900,
      lifeStage: "adult",
      habitatSummary: { en: "Open shelf water", de: "Offenes Schelfwasser" },
      behaviorSummary: { en: "A fast schooling swimmer that follows seasonal food.", de: "Eine schnelle Schwarmfischart, die saisonaler Nahrung folgt." },
      visualKey: "mackerel",
      illustrationAltText: { en: "Streamlined Atlantic mackerel with dark wavy dorsal markings and small finlets", de: "Stromlinienförmige Atlantische Makrele mit dunklen Wellenlinien am Rücken und kleinen Flösselchen" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 7,
      anatomicalTagLengthLimitMm: 22,
      studyRequirementId: "temperatureSeason",
      sourceIds: ["mackerel", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "cod-sam",
      individualName: "Sam",
      commonName: { en: "Atlantic cod", de: "Atlantischer Kabeljau" },
      scientificName: "Gadus morhua",
      taxonomicGroup: "teleost",
      lengthCm: 55,
      lengthType: "total",
      weightGrams: 1800,
      lifeStage: "subadult",
      habitatSummary: { en: "Rocky and mixed seabeds", de: "Felsige und gemischte Meeresböden" },
      behaviorSummary: { en: "Moves between seabed habitats and the water column.", de: "Wechselt zwischen Bodenhabitaten und der Wassersäule." },
      visualKey: "cod",
      illustrationAltText: { en: "Heavy-bodied Atlantic cod with three dorsal fins, pale lateral line and chin barbel", de: "Kräftiger Atlantischer Kabeljau mit drei Rückenflossen, heller Seitenlinie und Kinnfaden" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 10,
      anatomicalTagLengthLimitMm: 33,
      studyRequirementId: "depthYear",
      sourceIds: ["cod", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "cod-peter",
      individualName: "Peter",
      commonName: { en: "Atlantic cod", de: "Atlantischer Kabeljau" },
      scientificName: "Gadus morhua",
      taxonomicGroup: "teleost",
      lengthCm: 88,
      lengthType: "total",
      weightGrams: 6500,
      lifeStage: "adult",
      habitatSummary: { en: "Cold offshore shelf water", de: "Kaltes küstenfernes Schelfwasser" },
      behaviorSummary: { en: "Migrates among feeding, spawning and overwintering areas.", de: "Wandert zwischen Nahrungs-, Laich- und Überwinterungsgebieten." },
      visualKey: "cod",
      illustrationAltText: { en: "Large Atlantic cod with mottled body, three dorsal fins and chin barbel", de: "Großer Atlantischer Kabeljau mit geflecktem Körper, drei Rückenflossen und Kinnfaden" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 14,
      anatomicalTagLengthLimitMm: 45,
      studyRequirementId: "longTemperature",
      sourceIds: ["cod", "innovasea69", "jepsen2005"],
      difficultyRank: 3
    }),
    fish({
      id: "haddock-lina",
      individualName: "Lina",
      commonName: { en: "Haddock", de: "Schellfisch" },
      scientificName: "Melanogrammus aeglefinus",
      taxonomicGroup: "teleost",
      lengthCm: 58,
      lengthType: "total",
      weightGrams: 2400,
      lifeStage: "adult",
      habitatSummary: { en: "Continental shelf near the seabed", de: "Kontinentalschelf nahe dem Meeresboden" },
      behaviorSummary: { en: "Feeds on seabed invertebrates and small fishes.", de: "Frisst bodenlebende Wirbellose und kleine Fische." },
      visualKey: "haddock",
      illustrationAltText: { en: "Haddock with three dorsal fins, dark lateral line and black shoulder spot", de: "Schellfisch mit drei Rückenflossen, dunkler Seitenlinie und schwarzem Schulterfleck" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 10,
      anatomicalTagLengthLimitMm: 30,
      studyRequirementId: "migrationYear",
      sourceIds: ["haddock", "innovasea69", "jepsen2005"],
      difficultyRank: 2
    }),
    fish({
      id: "plaice-raya",
      individualName: "Raya",
      commonName: { en: "European plaice", de: "Europäische Scholle" },
      scientificName: "Pleuronectes platessa",
      taxonomicGroup: "teleost",
      lengthCm: 42,
      lengthType: "total",
      weightGrams: 1100,
      lifeStage: "adult",
      habitatSummary: { en: "Sandy and muddy seabeds", de: "Sandige und schlammige Meeresböden" },
      behaviorSummary: { en: "Rests flat on sediment and moves to feed.", de: "Ruht flach auf dem Sediment und zieht zur Nahrungssuche umher." },
      visualKey: "plaice",
      illustrationAltText: { en: "Flat oval European plaice with both eyes on one side and orange spots", de: "Flach-ovale Europäische Scholle mit beiden Augen auf einer Seite und orangefarbenen Punkten" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 7,
      anatomicalTagLengthLimitMm: 23,
      studyRequirementId: "temperatureSeason",
      sourceIds: ["plaice", "innovasea69", "jepsen2005"],
      difficultyRank: 2
    }),
    fish({
      id: "salmon-finn",
      individualName: "Finn",
      commonName: { en: "Atlantic salmon", de: "Atlantischer Lachs" },
      scientificName: "Salmo salar",
      taxonomicGroup: "teleost",
      lengthCm: 17.5,
      lengthType: "fork",
      weightGrams: 80,
      lifeStage: "juvenile",
      habitatSummary: { en: "River during seaward migration", de: "Fluss während der Abwanderung zum Meer" },
      behaviorSummary: { en: "A smolt preparing to move from freshwater to sea.", de: "Ein Smolt auf dem Weg vom Süßwasser ins Meer." },
      visualKey: "salmon",
      illustrationAltText: { en: "Slender silver Atlantic salmon smolt with small dark spots and adipose fin", de: "Schlanker silbriger Atlantischer Lachssmolt mit kleinen dunklen Flecken und Fettflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 6.3,
      anatomicalTagLengthLimitMm: 14,
      studyRequirementId: "shortPresence",
      sourceIds: ["salmon", "innovasea69", "jepsen2005"],
      difficultyRank: 1
    }),
    fish({
      id: "salmon-ada",
      individualName: "Ada",
      commonName: { en: "Atlantic salmon", de: "Atlantischer Lachs" },
      scientificName: "Salmo salar",
      taxonomicGroup: "teleost",
      lengthCm: 72,
      lengthType: "fork",
      weightGrams: 4200,
      lifeStage: "adult",
      habitatSummary: { en: "River and North Atlantic migration route", de: "Fluss und Wanderroute im Nordatlantik" },
      behaviorSummary: { en: "Moves between marine feeding areas and natal rivers.", de: "Wandert zwischen marinen Nahrungsgebieten und dem Heimatfluss." },
      visualKey: "salmon",
      illustrationAltText: { en: "Adult Atlantic salmon with streamlined silver body, dark spots and adipose fin", de: "Erwachsener Atlantischer Lachs mit stromlinienförmigem silbrigem Körper, dunklen Flecken und Fettflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 10,
      anatomicalTagLengthLimitMm: 32,
      studyRequirementId: "depthYear",
      sourceIds: ["salmon", "innovasea69", "jepsen2005"],
      difficultyRank: 2
    }),
    fish({
      id: "eel-elsa",
      individualName: "Elsa",
      commonName: { en: "European eel", de: "Europäischer Aal" },
      scientificName: "Anguilla anguilla",
      taxonomicGroup: "teleost",
      lengthCm: 68,
      lengthType: "total",
      weightGrams: 900,
      lifeStage: "adult",
      habitatSummary: { en: "Rivers, estuaries and coastal water", de: "Flüsse, Ästuare und Küstengewässer" },
      behaviorSummary: { en: "An elongated migrant that often travels at night.", de: "Ein langgestreckter Wanderfisch, der häufig nachts unterwegs ist." },
      visualKey: "eel",
      illustrationAltText: { en: "Long snake-like European eel with continuous dorsal and anal fin", de: "Langer schlangenförmiger Europäischer Aal mit durchgehender Rücken- und Afterflosse" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 7,
      anatomicalTagLengthLimitMm: 22,
      studyRequirementId: "temperatureSeason",
      sourceIds: ["eel", "innovasea69", "jepsen2005"],
      difficultyRank: 2
    }),
    fish({
      id: "seabass-leo",
      individualName: "Leo",
      commonName: { en: "European sea bass", de: "Europäischer Wolfsbarsch" },
      scientificName: "Dicentrarchus labrax",
      taxonomicGroup: "teleost",
      lengthCm: 55,
      lengthType: "total",
      weightGrams: 2200,
      lifeStage: "adult",
      habitatSummary: { en: "Estuaries and coastal shelf water", de: "Ästuare und küstennahes Schelfwasser" },
      behaviorSummary: { en: "Moves between coastal habitats and feeding areas.", de: "Wechselt zwischen Küstenhabitaten und Nahrungsgebieten." },
      visualKey: "seabass",
      illustrationAltText: { en: "European sea bass with streamlined silver body and two separate dorsal fins", de: "Europäischer Wolfsbarsch mit stromlinienförmigem silbrigem Körper und zwei getrennten Rückenflossen" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 10,
      anatomicalTagLengthLimitMm: 30,
      studyRequirementId: "migrationYear",
      sourceIds: ["seabass", "innovasea69", "jepsen2005"],
      difficultyRank: 2
    }),
    fish({
      id: "dogfish-otto",
      individualName: "Otto",
      commonName: { en: "Spiny dogfish", de: "Dornhai" },
      scientificName: "Squalus acanthias",
      taxonomicGroup: "shark",
      lengthCm: 95,
      lengthType: "total",
      weightGrams: 6500,
      lifeStage: "adult",
      habitatSummary: { en: "Shelf water near the seabed", de: "Schelfwasser nahe dem Meeresboden" },
      behaviorSummary: { en: "Often travels in groups and makes seasonal movements.", de: "Zieht häufig in Gruppen und unternimmt saisonale Wanderungen." },
      visualKey: "dogfish",
      illustrationAltText: { en: "Small shark with pointed snout, two dorsal fins with spines and heterocercal tail", de: "Kleiner Hai mit spitzer Schnauze, zwei bedornten Rückenflossen und heterocerker Schwanzflosse" },
      allowedAttachmentTypes: ["external"],
      anatomicalTagDiameterLimitMm: 18,
      anatomicalTagLengthLimitMm: 95,
      minimumExternalFishWeightGrams: 5000,
      studyRequirementId: "externalLong",
      sourceIds: ["dogfish", "innovasea69", "externalAttachment2022"],
      difficultyRank: 3
    }),
    fish({
      id: "catshark-kiki",
      individualName: "Kiki",
      commonName: { en: "Small-spotted catshark", de: "Kleingefleckter Katzenhai" },
      scientificName: "Scyliorhinus canicula",
      taxonomicGroup: "shark",
      lengthCm: 42,
      lengthType: "total",
      weightGrams: 700,
      lifeStage: "juvenile",
      habitatSummary: { en: "Rocky and sandy coastal seabed", de: "Felsiger und sandiger Küstenboden" },
      behaviorSummary: { en: "A small bottom-associated shark, often active at night.", de: "Ein kleiner bodennaher Hai, der häufig nachts aktiv ist." },
      visualKey: "catshark",
      illustrationAltText: { en: "Slender small-spotted catshark with many dark spots and a long upper tail lobe", de: "Schlanker kleingefleckter Katzenhai mit vielen dunklen Flecken und langem oberen Schwanzlappen" },
      allowedAttachmentTypes: ["external"],
      anatomicalTagDiameterLimitMm: 14,
      anatomicalTagLengthLimitMm: 60,
      minimumExternalFishWeightGrams: 5000,
      studyRequirementId: "externalLong",
      sourceIds: ["catshark", "innovasea69", "externalAttachment2022"],
      difficultyRank: 3
    }),
    fish({
      id: "tope-tara",
      individualName: "Tara",
      commonName: { en: "Tope shark", de: "Hundshai" },
      scientificName: "Galeorhinus galeus",
      taxonomicGroup: "shark",
      lengthCm: 145,
      lengthType: "total",
      weightGrams: 18000,
      lifeStage: "adult",
      habitatSummary: { en: "Coastal and offshore shelf water", de: "Küsten- und küstenfernes Schelfwasser" },
      behaviorSummary: { en: "A highly mobile shark capable of long migrations.", de: "Ein sehr mobiler Hai mit langen Wanderungen." },
      visualKey: "tope",
      illustrationAltText: { en: "Long streamlined tope shark with pointed snout and large heterocercal tail", de: "Langer stromlinienförmiger Hundshai mit spitzer Schnauze und großer heterocerker Schwanzflosse" },
      allowedAttachmentTypes: ["external"],
      anatomicalTagDiameterLimitMm: 20,
      anatomicalTagLengthLimitMm: 110,
      minimumExternalFishWeightGrams: 5000,
      studyRequirementId: "externalLong",
      sourceIds: ["tope", "innovasea69", "externalAttachment2022"],
      difficultyRank: 3
    }),
    fish({
      id: "thornback-mira",
      individualName: "Mira",
      commonName: { en: "Thornback ray", de: "Nagelrochen" },
      scientificName: "Raja clavata",
      taxonomicGroup: "ray",
      lengthCm: 85,
      lengthType: "disc-width",
      weightGrams: 9000,
      lifeStage: "adult",
      habitatSummary: { en: "Sandy, muddy and gravel seabeds", de: "Sandige, schlammige und kiesige Meeresböden" },
      behaviorSummary: { en: "Rests on sediment and moves across the seabed to feed.", de: "Ruht auf Sediment und bewegt sich zur Nahrungssuche über den Boden." },
      visualKey: "thornback",
      illustrationAltText: { en: "Broad diamond-shaped thornback ray viewed from above with dorsal eyes and a thorny tail", de: "Breiter rautenförmiger Nagelrochen von oben mit dorsalen Augen und dornigem Schwanz" },
      allowedAttachmentTypes: ["external"],
      anatomicalTagDiameterLimitMm: 20,
      anatomicalTagLengthLimitMm: 110,
      minimumExternalFishWeightGrams: 5000,
      studyRequirementId: "externalDepth",
      sourceIds: ["thornback", "innovasea69", "externalAttachment2022"],
      difficultyRank: 3
    }),
    fish({
      id: "spotted-ray-ina",
      individualName: "Ina",
      commonName: { en: "Spotted ray", de: "Fleckenrochen" },
      scientificName: "Raja montagui",
      taxonomicGroup: "ray",
      lengthCm: 65,
      lengthType: "disc-width",
      weightGrams: 6000,
      lifeStage: "subadult",
      habitatSummary: { en: "Sandy shelf seabed", de: "Sandiger Schelfboden" },
      behaviorSummary: { en: "A flattened bottom-dweller that can partly bury in sediment.", de: "Ein abgeflachter Bodenbewohner, der sich teilweise im Sediment eingraben kann." },
      visualKey: "spotted-ray",
      illustrationAltText: { en: "Rounded diamond-shaped spotted ray with dorsal eyes, pale spots and a slender tail", de: "Rundlich-rautenförmiger Fleckenrochen mit dorsalen Augen, hellen Flecken und schlankem Schwanz" },
      allowedAttachmentTypes: ["external"],
      anatomicalTagDiameterLimitMm: 20,
      anatomicalTagLengthLimitMm: 105,
      minimumExternalFishWeightGrams: 5000,
      studyRequirementId: "externalDepth",
      sourceIds: ["spottedRay", "innovasea69", "externalAttachment2022"],
      difficultyRank: 3
    }),
    fish({
      id: "pollack-jonas",
      individualName: "Jonas",
      commonName: { en: "Pollack", de: "Pollack" },
      scientificName: "Pollachius pollachius",
      taxonomicGroup: "teleost",
      lengthCm: 75,
      lengthType: "total",
      weightGrams: 3500,
      lifeStage: "adult",
      habitatSummary: { en: "Rocky reefs and coastal shelf water", de: "Felsriffe und küstennahes Schelfwasser" },
      behaviorSummary: { en: "Cruises around rocky structures and kelp edges.", de: "Zieht an Felsstrukturen und Kanten von Tangwäldern entlang." },
      visualKey: "pollack",
      illustrationAltText: { en: "Elongated pollack with three dorsal fins, projecting lower jaw and curved lateral line", de: "Langgestreckter Pollack mit drei Rückenflossen, vorstehendem Unterkiefer und gebogener Seitenlinie" },
      allowedAttachmentTypes: ["internal"],
      anatomicalTagDiameterLimitMm: 14,
      anatomicalTagLengthLimitMm: 40,
      studyRequirementId: "longMigration",
      sourceIds: ["pollack", "innovasea69", "jepsen2005"],
      difficultyRank: 3
    })
  ]);

  function fish(data) {
    return Object.freeze({ maxTagBurdenPercent: DEFAULT_MAX_TAG_BURDEN_PERCENT, ...data });
  }

  const DIFFICULTY_SETTINGS = Object.freeze({
    easy: Object.freeze({
      directMatchFishCount: 4,
      memoryPairCount: 4,
      fishPoolIds: ["herring-rose", "herring-henk", "mackerel-marta", "cod-sam", "plaice-raya", "salmon-finn"],
      mandatoryFishIds: ["herring-rose"],
      tagIds: ["v6", "v7tp", "v9tp"],
      showBurdenCalculation: true,
      showAttachmentHint: true,
      showStudyRequirementHints: true,
      memoryPreviewSeconds: 5
    }),
    medium: Object.freeze({
      directMatchFishCount: 6,
      memoryPairCount: 6,
      fishPoolIds: [
        "herring-rose", "herring-henk", "sprat-noor", "mackerel-marta", "cod-sam", "haddock-lina",
        "plaice-raya", "salmon-finn", "salmon-ada", "eel-elsa", "seabass-leo", "pollack-jonas"
      ],
      mandatoryFishIds: ["sprat-noor", "pollack-jonas"],
      tagIds: ["v6", "v7tp", "v9", "v9tp", "v13"],
      showBurdenCalculation: false,
      showAttachmentHint: true,
      showStudyRequirementHints: true,
      memoryPreviewSeconds: 3
    }),
    hard: Object.freeze({
      directMatchFishCount: 10,
      memoryPairCount: 10,
      fishPoolIds: FISH_CARDS.map((item) => item.id),
      mandatoryFishIds: ["catshark-kiki", "thornback-mira", "cod-peter"],
      tagIds: TAG_CATALOGUE.map((item) => item.id),
      showBurdenCalculation: false,
      showAttachmentHint: false,
      showStudyRequirementHints: false,
      memoryPreviewSeconds: 0
    })
  });

  const VISUAL_REFERENCE_CHECKLIST = Object.freeze([
    { key: "herring", species: "Atlantic herring", traits: "deep silvery body, blue-green back, single dorsal fin, forked tail" },
    { key: "sprat", species: "European sprat", traits: "small narrow clupeid body, silver sides, sharply forked tail" },
    { key: "mackerel", species: "Atlantic mackerel", traits: "streamlined body, wavy dark dorsal bands, deeply forked tail, finlets" },
    { key: "cod", species: "Atlantic cod", traits: "heavy body, three dorsal fins, pale lateral line, chin barbel" },
    { key: "haddock", species: "Haddock", traits: "three dorsal fins, dark lateral line, black shoulder spot" },
    { key: "plaice", species: "European plaice", traits: "flat oval body, both eyes on upper side, orange spots" },
    { key: "salmon", species: "Atlantic salmon", traits: "streamlined body, adipose fin, narrow caudal wrist, dark spots" },
    { key: "eel", species: "European eel", traits: "very elongated body, continuous median fins, small pectoral fins" },
    { key: "seabass", species: "European sea bass", traits: "silver fusiform body, two distinct dorsal fins, large mouth" },
    { key: "dogfish", species: "Spiny dogfish", traits: "small shark, dorsal spines, no anal fin, heterocercal tail" },
    { key: "catshark", species: "Small-spotted catshark", traits: "slender spotted shark, rear-set dorsal fins, long upper tail lobe" },
    { key: "tope", species: "Tope shark", traits: "long streamlined shark, pointed snout, large heterocercal tail" },
    { key: "thornback", species: "Thornback ray", traits: "broad angular disc, dorsal eyes, thorn row and long tail" },
    { key: "spotted-ray", species: "Spotted ray", traits: "rounded diamond disc, dorsal eyes, pale spots, slender tail" },
    { key: "pollack", species: "Pollack", traits: "elongated gadid, three dorsal fins, projecting lower jaw, curved lateral line" }
  ]);

  global.GameData = Object.freeze({
    ACCESSED_DATE,
    DEFAULT_MAX_TAG_BURDEN_PERCENT,
    SCIENCE_SOURCES,
    TAG_CATALOGUE,
    STUDY_REQUIREMENTS,
    FISH_CARDS,
    DIFFICULTY_SETTINGS,
    VISUAL_REFERENCE_CHECKLIST,
    TOO_SMALL_ID: "too-small"
  });
})(globalThis);
